FROM python:3.9-slim

ENV PORT 5000
ENV host 0.0.0.0
ENV PYTHONUNBUFFERED True

EXPOSE 5000

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install --verbose --no-cache-dir -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app

